apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage
spec:
  capacity:
    storage: 3Gi
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-storageclass
  nfs: 
    path: /nfsshare/
    server: 192.168.122.1
