apiVersion: v1
kind: Service
metadata:
  name: "jboss-service1"
  labels:
    {{- include "jboss-1.0.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: 192.168.144.155
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jboss-1.0.selectorLabels" . | nindent 4 }}
