apiVersion: v1
kind: Service
metadata:
  name: wildfly-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: wildfly
  type: NodePort
status:
  loadBalancer: {}
