apiVersion: v1
kind: Service
metadata:
  name: wildfly-svc
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
    name: http
  selector:
    app: wildfly
status:
  loadBalancer: {}