apiVersion: v1
kind: Service
metadata:
  name: wildfly-svc1
spec:
  ports:
  - port: 9990
    targetPort: 9990
    nodePort: 30001
  selector:
    app: wildfly
  type: NodePort
status:
  loadBalancer: {}
